name: Test

on: [push, pull_request]

jobs:
  phpcs:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [ 8.0, 8.1, 8.2 ]
    
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-version }}
          args: --ignore-platform-reqs
      - name: Run WordPress code standard
        run: |
          ./vendor/bin/phpcs --ignore=vendor,wpcs --standard=./phpcs.xml ./
